In [1]:
# Import package and set environment
import numpy as np

In [22]:
### PROBLEM 1

A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])

np.dot(A, B)
#A @ B

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [36]:
### PROBLEM 2

A = np.array([[3,1,4], [1,5,9], [-5,3,1]])

- np.dot(A,np.dot(A,A))+ 9 * np.dot(A,A) - 15*A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [72]:
### PROBLEM 3

A = np.triu(np.ones((7)))
B = (5 * np.ones((7,7)) - 6 * np.tril(np.ones((7))))

x = np.dot(A, np.dot(A,B))
x = x.astype(np.int64)
print(x)

[[-28 -22 -10   8  32  62  98]
 [-21 -21 -15  -3  15  39  69]
 [-15 -15 -15  -9   3  21  45]
 [-10 -10 -10 -10  -4   8  26]
 [ -6  -6  -6  -6  -6   0  12]
 [ -3  -3  -3  -3  -3  -3   3]
 [ -1  -1  -1  -1  -1  -1  -1]]


In [90]:
### PROBLEM 4

array = np.array([1,2,3, -1, -2])

def function_pb4(array):
    c = np.copy(array)
    c[c < 0] = 0
    print(c)

In [169]:
### PROBLEM 5

def function_pb5():
    # Create the 3 matrices
    A = np.arange(6).reshape((3,2)).T
    B = 3*np.tril(np.ones(3))
    C = -2 * np.diag(np.ones(3))
    
    print(np.vstack((np.hstack((np.zeros((3,2)), A.T, np.diag((np.ones(3))))),
           np.hstack((A, np.zeros((2,2)), np.zeros((2,2)))),
           np.hstack((B, np.zeros((3,1)), C)))))


In [253]:
### PROBLEM 6

def function_pb6(matrix):
    matrix_new = matrix / matrix.sum(axis=1).reshape(-1,1)
    print(matrix_new)


In [388]:
### PROBLEM 7

grid = np.load("grid.npy")

horiz = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
vert = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
diag_r = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
diag_l = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
winner = max(horiz, vert, diag_r, diag_l)

print(winner)

70600674
